# Generated by Django 5.0.7 on 2024-07-14 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='Subcategories',
        ),
    ]
