# Generated by Django 5.0.7 on 2024-07-14 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_articles_subcategory_delete_subcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='template',
            field=models.BooleanField(default=False, verbose_name='Template'),
        ),
    ]
