# Generated by Django 5.0.7 on 2024-07-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articles_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='sponsor',
            field=models.CharField(blank=True, default='Sponsor', max_length=200, null=True, verbose_name='Sponsor'),
        ),
    ]
