# Generated by Django 5.0.7 on 2024-07-14 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_articles_sponsor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='template',
        ),
    ]
