# Generated by Django 5.0.7 on 2024-07-14 21:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_remove_articles_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='txt',
            field=ckeditor.fields.RichTextField(default='', verbose_name='Text'),
        ),
    ]
