# Generated by Django 5.0.7 on 2024-07-14 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_articles_txt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='sponsor',
        ),
    ]
