# Generated by Django 5.0.7 on 2024-07-15 02:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_remove_articles_sponsor'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='name_az',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='articles',
            name='name_en',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='articles',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='articles',
            name='txt_az',
            field=ckeditor.fields.RichTextField(default='', null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='articles',
            name='txt_en',
            field=ckeditor.fields.RichTextField(default='', null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='articles',
            name='txt_ru',
            field=ckeditor.fields.RichTextField(default='', null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='categories',
            name='name_az',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='categories',
            name='name_en',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='categories',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Title'),
        ),
    ]
