# Generated by Django 5.0.7 on 2024-07-18 18:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('name_az', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Name')),
                ('txt', ckeditor.fields.RichTextField(verbose_name='About me')),
                ('txt_az', ckeditor.fields.RichTextField(null=True, verbose_name='About me')),
                ('txt_en', ckeditor.fields.RichTextField(null=True, verbose_name='About me')),
                ('txt_ru', ckeditor.fields.RichTextField(null=True, verbose_name='About me')),
                ('img', models.URLField(default='', verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'About me',
                'verbose_name_plural': 'About me',
            },
        ),
    ]
