# Generated by Django 5.0.7 on 2024-07-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='img',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Foto'),
        ),
    ]
